spring:
  mail:
#    protocol: smtp
#    host: smtp.yandex.ru
#    port: 587
    host: imap.yandex.ru
    protocol: imap
    port: 993
    username: info@denttime.ru
    password: 23Ja8Uq(
    properties:
      mail:
        smtp: auth=true
        starttls: enable=true

mail:
  mime:encodeparameters: false
  mime:charset: utf-8

file:download:location: D:\\temp\\mail
mailFolderName: INBOX
mailsListSize: 300
#listsUrl : "D:\\temp\\mail\\"
listsUrl : ""

bestdoctor:
  storage: "BestDoctor.xlsx"
  sender: "list@bestdoctor.ru"
  liststemplate: "СПИСКИ"
  attachlisttemplate: "ПРИКРЕПЛЕНИЕ"
  deattachlisttemplate: "ОТКРЕПЛЕНИЕ"
  attachfiletemplate: "ПРИКРЕПЛЕНИЕ"
  deattachfiletemplate: "ОТКРЕПЛЕНИЕ"

alfastrah:
  storage: "AlfaStrah.xlsx"
  sender: "avis@alfastrah.ru"
  liststemplate: "СПИСКИ"
  attachlisttemplate: "ПРИКРЕПЛЕНИЕ"
  deattachlisttemplate: "ОТКРЕПЛЕНИЕ"
  attachfiletemplate: "prikr"
  deattachfiletemplate: "snyat"

rosgosstrah:
  storage: "RosGosStrah.xlsx"
  sender: "spiski@rgs.ru"
  liststemplate: "СПИСОК ЗАСТРАХОВАННЫХ"
  attachlisttemplate:
  deattachlisttemplate:
  attachfiletemplate: " ПР "
  deattachfiletemplate: " ОТКР "

ingosstrah:
  storage: "InGosStrah.xlsx"
  sender: "@ingos.ru"
  liststemplate: "СПИСКИ"
  attachlisttemplate: "ПРИКРЕПЛЕНИЯ"
  deattachlisttemplate: "ОТКРЕПЛЕНИЯ"
  attachfiletemplate: "ПРИКР"
  deattachfiletemplate: "ОТКР"

absolut:
  storage: "Absolut.xlsx"
  sender: "@absolutins.ru"
  liststemplate: "СПИСОК"
  attachlisttemplate: "ПРИНЯТИЕ"
  attachlisttemplate2: "ПРИКРЕПЛЕНИЕ"
  deattachlisttemplate: "СНЯТИЕ"
  deattachlisttemplate2: "ОТКРЕПЛЕНИЕ"
  attachfiletemplate: "ПРИНЯТИЕ"
  attachfiletemplate2: "ПРИКРЕПЛЕНИЕ"
  deattachfiletemplate: "ОТКРЕПЛЕНИЕ"
  deattachfiletemplate2: "СНЯТИЕ"

sogaz:
  storage: "Sogaz.xlsx"
  sender: "robotlpu@sogaz.ru"
  liststemplate: "СПИСКИ"
  attachlisttemplate: "ПРИКРЕПЛЕНИЕ"
  deattachlisttemplate: "ОТКРЕПЛЕНИЕ"
  attachfiletemplate: ".XLS"
  deattachfiletemplate: ".XLS"

soglasie:
  storage: "Soglasie.xlsx"
  sender: "spiski_lpu@soglasie.ru"
  liststemplate: "СК СОГЛАСИЕ"
  attachlisttemplate: "СПИСОК"
  deattachlisttemplate: "СПИСОК"
  attachfiletemplate: "ПРИКР"
  deattachfiletemplate: "ОТКР"

reso:
  storage: "Reso.xlsx"
  sender: "mural@reso.ru"
  liststemplate: "РЕСО-Гарантия"
  attachlisttemplate: "ПРИКРЕПЛЕНИЕ"
  deattachlisttemplate: "ОТКРЕПЛЕНИЕ"
  attachfiletemplate: ".RTF"
  deattachfiletemplate: ".RTF"

renaissance:
  storage: "Renaissance.xlsx"
  sender: "spiskilpu@renins.com"
  liststemplate: ""
  attachlisttemplate: "_прикр_"
  deattachlisttemplate: "_откр_"
  attachfiletemplate: "_прикр_"
  deattachfiletemplate: "_откр_"

