spring:
  mail:
    host: smtp.yandex.ru
    port: 587
    username: info@denttime.ru
    password: 23Ja8Uq(
    properties:
      mail:
        smtp: auth=true
        starttls: enable=true

logging:
  level:org:springframework:web: INFO
  level:net:guides: DEBUG
  file:name: logs/dms.log

mail:
  mime:encodeparameters: false
  mime:charset: utf-8

file:download:location: D:\\temp\\mail
mail:folder:name: FOO

mailslistsize: 450

bestdoctor:
  storage: D:\\temp\\mail\\BestDoctor.xlsx
  sender: list@bestdoctor.ru
  liststemplate: СПИСКИ
  attachlisttemplate: ПРИКРЕПЛЕНИЕ
  deattachlisttemplate: ОТКРЕПЛЕНИЕ
  attachfiletemplate: ПРИКРЕПЛЕНИЕ
  deattachfiletemplate: ОТКРЕПЛЕНИЕ

alfastrah:
  storage: D:\\temp\\mail\\AlfaStrah.xlsx
  sender: avis@alfastrah.ru
  liststemplate: СПИСКИ
  attachlisttemplate: ПРИКРЕПЛЕНИЕ
  deattachlisttemplate: ОТКРЕПЛЕНИЕ
  attachfiletemplate: prikr
  deattachfiletemplate: snyat

rosgosstrah:
  storage: D:\\temp\\mail\\RosGosStrah.xlsx
  sender: spiski@rgs.ru
  liststemplate: СПИСОК ЗАСТРАХОВАННЫХ
  attachlisttemplate:
  deattachlisttemplate:
  attachfiletemplate: " ПР "
  deattachfiletemplate: " ОТКР "

